version: 2.1
executors:
  default:
    working_directory: ~/app
    docker:
      - image: circleci/openjdk:11-jdk

jobs:
  build:
    executor: default
    steps:
      - checkout

      - run:
          name: Set execution permission for gradlew
          command: chmod +x gradlew

      - run:
          name: Display Java version
          command: java -version

      - run:
          name: Display Gradle version
          command: ./gradlew --version

      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle

      - run:
          name: Clean project
          command: ./gradlew clean

      - run:
          name: Build project
          command: ./gradlew assembleRelease --warning-mode all --stacktrace

      - run:
          name: Run unit tests
          command: ./gradlew testDebugUnitTest --stacktrace

      - save_cache:
          key: jars-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle

      - store_artifacts:
          path: app/build/outputs/apk/release/
          destination: apks

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
