version: 2.1
jobs:
  build:
    docker:
      - image: circleci/android:api-30
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      
      - run:
          name: Display Gradle version
          command: ./gradlew --version

      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      
      - run:
          name: Build project
          command: ./gradlew build --warning-mode all
      
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: apks

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
